version: "3"
services:
  postgres:
    container_name: modular_dev
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      # - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
